version: "3"

services:
    client_worker:
        container_name: client_worker
        image: ailin/client_worker
        restart: always
        privileged: true
        network_mode: "host"
        env_file: client_variables.env
        environment:
            - DISPLAY=unix${DISPLAY}
        command: ./start.sh
        ports:
            - "514:10514"
            - "514:10514/udp"
        depends_on:
            - redis
        volumes:
            - /usr/share/client/logs:/usr/share/client/logs
            - /var/DevTesting/:/var/DevTesting/
            - /var/streams/:/var/streams/
            - /usr/share/lstreamer/:/usr/share/lstreamer

            - /tmp/.X11-unix:/tmp/.X11-unix
            - /dev/:/dev/
            - /sys/:/sys/

    redis:
        hostname: redis
        container_name: client_redis
        image: redis
        restart: always
        network_mode: "host"
